### PR TITLE
Apply modification to improve library setup

### LINKED ISSUE #4: Basics tests for optional, expected are Hello World examples
While reviewing the submitted packages I noticed that the basic test in both `tl-optional` and `tl-expected` is a generated Hello World example that was modified to just include the library header. While there are proper external tests, it's still a good idea to exerciser at least the most basic functionality (say, for optional, create an instance with a value and assert that there is a value, something like this). Also having Hello World code and even testing it with a `testscript` is kind of a waste and will probably be confusing to anyone looking at, it sure was to me.

Finally, while `tl-optional` follows the canonical setup for the basic test (i.e, it's inside a subproject called `tests`), `tl-expected` for some reason has just a subdirectory called `basic-test` (which means it can't be used to test the installed version of the library).

Also, while at, it would be good to fix the `license` id in manifest to `CC0-1.0` (per https://spdx.org/licenses/).

### PR DESCRIPTION
**Pull request by Wmbat**
[CI](https://ci.cppget.org/@1c5fc9d6-7045-4246-8e0d-730cb9fc8f4d?builds=&pv=&tc=*&cf=&mn=&tg=&rs=error)

- The basic tests for optional and expected now actually use optional & expected but they don't actually do much
- Modified instances of CC0 1.0 to CC0-1.0

### CODE REVIEW

**Comment by boris-kolpackov** [comment]
LGTM

**Comment by Klaim** [comment]
@Wmbat Would you have time to rebase this soon?

**Review by boris-kolpackov — APPROVED** [review]

**Comment by Klaim** [comment]
I think @Wmbat is too occupied, I'll try to handle the 2 PRs here soon. 👍🏽

**Comment by boris-kolpackov** [comment]
Sounds good to me.

**Pull request merged**
