### PR TITLE
Added tl::generator to the tl library package

### LINKED ISSUE #6: Consider adding `tl::generator`
See: 
 - https://tl.tartanllama.xyz/en/latest/api/generator.html
 - https://github.com/TartanLlama/generator

### PR DESCRIPTION
**Pull request by Wmbat**
Aims to add the `tl::generator` library to the tl library

### CODE REVIEW

**Comment by Wmbat** [comment]
Most of the work is done. The last thing holding me back in that i'm getting this error when running `b test`:
```
error: no rule to update (for test) ../gcc-debug/fsdir{tl-generator/}
  info: target ../gcc-debug/fsdir{tl-generator/} is not declared in any buildfile
  info: re-run with --verbose=4 for more information
  info: while applying rule build.alias to update (for test) ../gcc-debug/dir{tl-generator/}
  info: while applying rule test to update (for test) dir{./}
info: failed to update (for test) dir{./}
```

I'll have to investigate further why it's happening

**Comment by Klaim** [comment]
Wow thanks for adding this so fast XD

Other than that issue, LGTM
I'll try the PR soon

**Comment by Wmbat** [comment]
Things to do (mostly a reference for future me 😀):

- [x] Update readme to include `tl::generator`
- [x] Fix `b test` error
- [ ] Disable clang CI for `tl-generator-tests` because the library does not support clang (yet)

**Comment by Klaim** [comment]
I'm seeing another error on windows with `bdep test -a`:
```
<buildspec>: error: target ..\build-msvc\tl-generator\ does not support operation test
```

That's because `tl-generator` dont have any test, not even the basic one you can find in `tl-expected` for example (because of an issue with `build2` requiring testable projects when using `bdep test`, I think we discussed that before and there is an issue somewhere already)

I'll fix it quickly.

**Comment by Klaim** [comment]
Now I just get failing tests but I suspect it might be because I have the MSVC Preview versions installed. Either that or there is an issue with this version.

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tl-generator-tests.exe is a Catch v2.13.9 host application.
Run with -? for options

-------------------------------------------------------------------------------
split
-------------------------------------------------------------------------------
E:\projects\build2-packaging\tl\build2-tl\tl-generator-tests\tl-generator-tests\test.cpp(77)
...............................................................................

E:\projects\build2-packaging\tl\build2-tl\tl-generator-tests\tl-generator-tests\test.cpp(77): FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:  3 |  2 passed | 1 failed
assertions: 41 | 40 passed | 1 failed
```

**Comment by Klaim** [comment]
I'm seeing other issues with clang-15/mscv-preview, not sure if it's the toolchain, we'll see with the CI I guess.

**Comment by Wmbat** [comment]
> 

I've pulled your changes and i'm also getting a segmentation violation signal with GCC 12.2.1

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tl-generator-tests is a Catch v2.13.9 host application.
Run with -? for options

-------------------------------------------------------------------------------
split
-------------------------------------------------------------------------------
/home/wmbat/software-dev/build2-ports/tl/tl/tl-generator-tests/tl-generator-tests/test.cpp:77
...............................................................................

/home/wmbat/software-dev/build2-ports/tl/tl/tl-generator-tests/tl-generator-tests/test.cpp:77: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:  3 |  2 passed | 1 failed
assertions: 41 | 40 passed | 1 failed
```

**Comment by Klaim** [comment]
Interesting. Note that the code states that the project have only been tested with msvc, but it's interesting that you get the same issue was with msvc on gcc.

Anyway I think at this point we need some guidance from the author, I contacted them already to ask if there is somethnig to know about the state of the project.

**Comment by Klaim** [comment]
~~We were not using the last `main` version where fixes of the tests were present. The author also pointed they did fix the tests.~~

He merged the fixed that were present on another branch, so this commit updates our upstream accordingly.

**Comment by Klaim** [comment]
Clang will not be supported for now, it's missing C++20 features. So we should try to not build this specific package there. (I'll get back to this later if you dont already)

I also asked the Sy (the author) about potentially tagging the version so that we can track it.

**Comment by Klaim** [comment]
Sy just tagged v0.4.0 so we can track that now. 👍🏽

**Comment by Klaim** [comment]
About restricting clang build: It actually builds and run for me on clang-15/msvc-preview , so we might want to check on clang-15/linux  and then if it works restrict just to clang-15 or higher.

**Comment by Klaim** [comment]
@Wmbat We might have an issue for the tagging side of things: generator is `v0.4.0` but the other packages are `v1.0.0` and also they are tagged "in sync" right now. As long as we dont add new tags it should be fine but it's kind of suggesting we might want to splitt at least tl-generator in a new repo later? Not sure if it's a real problem.

**Comment by Wmbat** [comment]
I'm fine with no longer adding new tags to this repo. I think it makes more sense to keep all the libraries together as they all end up being installed at the same location and all fall under the foldel `tl`

**Comment by Wmbat** [comment]
> About restricting clang build: It actually builds and run for me on clang-15/msvc-preview , so we might want to check on clang-15/linux and then if it works restrict just to clang-15 or higher.

For clang 15.0.7, i get problems with missing `typename` specifiers in some places. This should be resolved with the upcoming clang 16 release though

**Comment by Klaim** [comment]
> I'm fine with no longer adding new tags to this repo. I think it makes more sense to keep all the libraries together as they all end up being installed at the same location and all fall under the foldel `tl`

Ok lets do that then.



> > About restricting clang build: It actually builds and run for me on clang-15/msvc-preview , so we might want to check on clang-15/linux and then if it works restrict just to clang-15 or higher.
> 
> For clang 15.0.7, i get problems with missing `typename` specifiers in some places. This should be resolved with the upcoming clang 16 release though

Ok then should we completely deactivate clang for now?
Also I looked qucikly at the workflow file and I think we could de-initialize only `tl-generator*` packages before building IFF the toolchain is clang (for now.

BTW when I posted I also tried to `bdep ci` only these packages, see what will result but I hit a weird error:
```bash
Klaim@KLAIMSTATION2 MINGW64 /e/projects/build2-packaging/tl/build2-tl (tl-generator)
$ bdep ci -d ./tl-generator/ -d ./tl-generator-tests/
submitting:
  to:      https://ci.stage.build2.org
  in:      https://github.com/Wmbat/build2-tl.git#tl-generator@87da071ee0303740dd3eeb1b5e325011668de62f

  package: tl-generator
  version: 0.4.0

  package: tl-generator-tests
  version: 0.4.0
continue? [y/n] y
############################################################################################################# 100.0%
error: unable to fetch repository information (run 'bpkg rep-info --deep --manifest https://github.com/Wmbat/build2-tl.git#tl-generator@87da071ee0303740dd3eeb1b5e325011668de62f' for details)
  info: reference: ad9929a3-452a-422d-982f-7d43eb6ff82e

Klaim@KLAIMSTATION2 MINGW64 /e/projects/build2-packaging/tl/build2-tl (tl-generator)
$ bpkg rep-info --deep --manifest https://github.com/Wmbat/build2-tl.git#tl-generator@87da071ee0303740dd3eeb1b5e325011668de62f
fetching from https://github.com/Wmbat/build2-tl.git
remote: Enumerating objects: 122, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 122 (delta 18), reused 97 (delta 4), pack-reused 0
fetching submodule 'upstream-expected' from https://github.com/TartanLlama/expected
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 29 (delta 2), reused 13 (delta 0), pack-reused 0
submodule path 'upstream-expected': checked out '96d547c03d2feab8db64c53c3744a9b4a7c8f2c5'
fetching submodule 'upstream-expected/cmake/tl-cmake' from https://github.com/TartanLlama/tl-cmake.git
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 2 (delta 0), pack-reused 0
submodule path 'upstream-expected/cmake/tl-cmake': checked out '284c6a3f0f61823cc3871b0f193e8df699e2c4ce'
fetching submodule 'upstream-optional' from https://github.com/TartanLlama/optional
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 31 (delta 0), reused 11 (delta 0), pack-reused 0
error: unable to deduce commit for submodule cmake/tl-cmake
  info: re-run with -v for more information
```

Could you try on your side? I have no idea why `cmake/tl-cmake` is being considered but it might be an issue with `build2` staging version.

**Comment by Klaim** [comment]
> BTW when I posted I also tried to bdep ci only these packages, see what will result but I hit a weird error:

#9

**Comment by Klaim** [comment]
For testing on `build2`'s CI:
The fixes for #9 requires updating the upstreams for the other dependencies, including `tl-optional` which have a new version and `tl-expected` which have not a new version but which branch have the commit removing the issue.

So until both are available I guess we'll have to wait. That's unfortunate but that's what submodules does XD

**Comment by Klaim** [comment]
I rebased this branch over #10 as it's an indirect requirement (tl-generator dont need these but we need it's commits to be over the changes to submodule that was made upstream), to see the CI results.

**Comment by Klaim** [comment]
`build2`'s CI : https://ci.stage.build2.org/@29101a20-a70d-4bb0-b2af-2a79dd98829b

I only sent `tl-generator` and `tl-generator-tests`

**Comment by Klaim** [comment]
We'll need to increase the required clang version for tl-generator.

**Comment by Klaim** [comment]
This works for me locally on windows with clang-16 and msvc, but I still need to fix the clang exclusion etc. for ci (for tl-generator only).

**Comment by Klaim** [comment]
build2's ci looks good with this version https://ci.stage.build2.org/@754420ef-b9be-4f39-874a-692a97fe0cef?builds=&pv=&th=*&tg=&tc=&pc=&rs=*

Only thing missing is making github's ci work. Not sure how to exclude clang build on non-windows but only for tl-generator. I considered several strategies locally but none is easy to maintain.
I'll find something.

**Comment by Klaim** [comment]
I finally managed to properly filter `tl-generator` from the ci depending on the platform/compiler, I'll squash these ci fix commits now.

**Comment by Klaim** [comment]
I will merge this and publish the versions.
Feel free to add some reviews afterwards if you find the time, we can always make revision packages.

**Review by Klaim — APPROVED** [review]
(disclaimer: I also helped with this pr)

**Pull request merged**
